print("personal info")
name= input("enter your name:")
age= input("enter your age:")
colour= input("enter you favourite colour:")
hobby= input("enter your hobby:")
print("\n your personal info card")
print("name:", name)
print("age:", age)
print("colour:", colour)
print("hobby:", hobby)
