print("movie card")
movie= input("enter your fav movie:")
year= input("enter the year the movie got released:")
actor= input("enter the fav actor in this movie:")
actress= input("enter the fav actress in this movie:")
rating= input("enter the rating you are giving fo the movie out of 10:")
print("movie card")
print("movie:",movie)
print("year:",year)
print("actor:",actor)
print("actress:",actress)
print("rating:",rating)